#!/bin/zsh

# Commands
alias ls='ls --color'
alias vim=nvim

# Save and load paths
alias savepath="pwd > /tmp/savepath"
alias loadpath="[ -f /tmp/savepath ] && \`cat /tmp/savepath\` || echo /tmp/savepath does not exist."

# Git aliases
alias gupp="git fetch && git rebase && git push"
alias gl='git pull --rebase'
alias gdc='git diff --cached'

# Common mistypings
alias mkae="make"
alias maek="make"
alias rkae="rake"
alias raek="rake"
alias sprunge="curl -F 'sprunge=<-' http://sprunge.us 2>/dev/null|pbcopy"

# Fuzzy cd
function fcd() {
  local dir
  dir=$(
    fd \
      --type directory |
        fzf \
          --bind 'focus:transform-preview-label:echo [ {} ]' \
          --preview 'tree -C -L 1 {} || ls --color=always {}' \
          --query="$*"
  )
  [[ -n "${dir}" ]] && cd "${dir}"
}
